[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501

[theme]
base = "light"
primaryColor = "#007BFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#000000"
font = "sans serif"
